contact_links:
  - name: "Discussions"
    url: https://github.com/petersenpeter/CellExplorer/discussions
    about: For any other questions - including if you are unsure about how to perform a given action.
  - name: "Online tutorials"
    url: https://cellexplorer.org/tutorials/tutorials/
    about: Did you check out the tutorials to help you get started using CellExplorer?
    
