contact_links:
  - name: "Discussion forum"
    url: https://github.com/petersenpeter/CellExplorer/discussions
    about: Other questions, including if you're not sure what to do.
  - name: "Online tutorials"
    url: https://cellexplorer.org/tutorials/tutorials/
    about: Tutorials to help you get started using CellExplorer.
    
